# -*- coding: utf-8 -*-
"""pratica_2_especializacao_geotecnologias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qjn6YET7FMNhO54b9EbTLj9fVA9Jqp3I

Introdução à Linguagem de Programação Python
"""

# Declarando variáveis
x = 10
y = 20.3
z = 'variavel'
w = z

# Identificadores de objetos no Python
id(z)

id(w)

id(z) == id(w)

# Tipo de variáveis
type(x)

type(y)

type(z)

# Operações matemáticas
x + int(y)

x + y # retorna número do tipo float, caso precise ser inteiro, é necessário converter a variável de float para int

str(x) + z

str(y) + w

x + z  # Não podemos fazer operações entre números e string