# -*- coding: utf-8 -*-
"""pratica_especializacao_geotecnologias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ChnHXpyCXUG6catudwlxfg_6A2ChY_1M
"""

"Hello, World!"

print("My name is Jeanne")

# Orientações sobre o ambiente Google Colab:
## Na barra lateral esquerda temos acesso a pasta com arquivos de amostras "sample_data"
## Nessa pasta temos diversos conjuntos de dados que são anexos do Google Colab
## Também temos acesso a pasta para conectra com o Google Drive

# Alguns bibliotecas do Python já vem pré-instaladas no Colab
import numpy as np # pacote usado para cálculos
import pandas as pd # pacote usado para ciência de dados
import matplotlib.pyplot as plt # pacote usado para visualização de dados