# -*- coding: utf-8 -*-
"""pratica_especializacao_geotecnologias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ChnHXpyCXUG6catudwlxfg_6A2ChY_1M
"""

"Hello, World!"

print("My name is Jeanne")

# Orientações sobre o ambiente Google Colab:
## Na barra lateral esquerda temos acesso a pasta com arquivos de amostras "sample_data"
## Nessa pasta temos diversos conjuntos de dados que são anexos do Google Colab
## Também temos acesso a pasta para conectra com o Google Drive

# Alguns bibliotecas do Python já vem pré-instaladas no Colab
import numpy as np # pacote usado para cálculos
import pandas as pd # pacote usado para ciência de dados
import matplotlib.pyplot as plt # pacote usado para visualização de dados

df = pd.read_csv("/content/sample_data/california_housing_test.csv")

df.head() # apresenra as cinco primeiras linhas do data frame

df.tail() # visualizar os últimos dados da tabela

df.columns # visualizar nomes das colunas

df.head(10) # apresenta os 10 primeiros registros da tabela

np.mean(df['median_income']) # calcula a média dos dados de uma coluna

print(np.mean(df['median_income'])) # o print permite inserir apenas o resultado

print(np.var(df["median_income"])) # calcula a variância

print(np.std(df['median_income'])) # calcula o desvio padrão

df.describe() # permite analisar todo o resumo estatístico da tabela de dados

df['median_income'].describe()

print("Média da renda salarial da população:", np.mean(df['median_income']))