# -*- coding: utf-8 -*-
"""pratica_2_especializacao_geotecnologias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qjn6YET7FMNhO54b9EbTLj9fVA9Jqp3I

Introdução à Linguagem de Programação Python
"""

# Declarando variáveis
x = 10
y = 20.3
z = 'variavel'
w = z

# Identificadores de objetos no Python
id(z)

id(w)

id(z) == id(w)

# Tipo de variáveis
type(x)

type(y)

type(z)

# Operações matemáticas
x + int(y)

x + y # retorna número do tipo float, caso precise ser inteiro, é necessário converter a variável de float para int

str(x) + z

str(y) + w

x + z  # Não podemos fazer operações entre números e string

# Estruturas de dados
d = {'nome': 'Jeanne', 'idade': 36, 'estado': 'RN'}

type(d)

d.keys()

d['nome']

d['estado']

L = [1,2,3,4,5]
type(L)

L[2] # retorna o valor localizado na terceira posição, pois no python inicia-se em 0

L[-1] # retorna o último elemento

L[-2] # retorna o penúltimo elemento

T = (520, 'coordenadas geográficas', 20, 84999781275) # a tuppla se diferencia da lista por não ser dinâmico, ou seja, os dados não são alterados, na lista pode ser modificado, por exemplo, lista de compras, lista de tarefas, etc
T

type(T)

T[2]

# Estrutura de condição
x = -45
y = -15

if (x > 0) and (y > 0): # após dois pontos e enter ocorre a identação necessária para correr o código
  print('Hemisfério norte')
else:
  print('Hemisfério sul')

x = -45
y = -15

if (x > 0) and (y > 0):
  print('Hemisfério norte')
elif (x == 0) and (y==0): # condição adicional intermediária
  print('Origem')
else:
  print('Hemisfério sul')

x = 0
y = 0

if (x > 0) and (y > 0):
  print('Hemisfério norte')
elif (x == 0) and (y==0): # condição adicional intermediária
  print('Origem')
else:
  print('Hemisfério sul')

"""Estruturas de repetição

"""

# Bibliotecas
import numpy as np

# Criando uma lista com a biblioteca numpy
lista = list(np.random.rand(100)) # cria 100 números aleatórios variando de 0 a 1
lista

lista2 = list(np.random.randint(1, 100, 100)) # gera 100 números inteiros variando de 1 a 100
lista2

# Loop do tipo for
for i in lista:
  print(i)

for i in lista: # passa por todos os elementos, 'printa' e soma + 1 em cada valor
  print(i + 1)

# Criar nova lista cujo resultado seja o somatório de +2 em cada valor presente na primeira lista

## Primeira forma:

lista_soma = []

for i in lista:
  lista_soma.append(i  + 2)

print(lista_soma)

# Comprimento de listas e alcances
len(lista)

range(len(lista))

## Segunda forma:

lista_soma_2 = []

for i in range(len(lista)):
  lista_soma_2.append(lista[i] + 4) # a função vai modificar o valor em cada posição da lista, por isso, lista[i]

print(lista_soma_2)

## Função insert:

lista_satelites = ['modis', 'landsat', 'amazonia']

lista_satelites.insert(3, 'sentinel') # inserir 'sentinel' na posição 3

print(lista_satelites)

# Loop com while

lista_com_while = []

contador = 0

while contador < len(lista): # enquanto o contador apresentar um valor menor do que o comprimento da lista (100), ele adiciona +1 a cada valor da lista
  lista_com_while.append(lista[contador] + 1)
  contador += 1 # como foi definido que o contador começa na posição zero, após a soma, ele vai para a posição 1, e assim por diante até somar todos os valores da lista

print(lista_com_while)

"""Numpy array (listas e tuplas com a biblioteca numpy)"""

# Criando uma lista com numpy
np.array([1, 2, 3, 4, 5])

lista_array = np.array(['a', 'b', 'c', 'd'])
print(lista_array)

# Criando uma matriz

matriz = np.array([[5, 7, 3, 5], [9, 3, 4, 1]]) # necessário um colchete a mais global
print(matriz)