# -*- coding: utf-8 -*-
"""pratica_2_especializacao_geotecnologias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qjn6YET7FMNhO54b9EbTLj9fVA9Jqp3I

Introdução à Linguagem de Programação Python
"""

# Declarando variáveis
x = 10
y = 20.3
z = 'variavel'
w = z

# Identificadores de objetos no Python
id(z)

id(w)

id(z) == id(w)

# Tipo de variáveis
type(x)

type(y)

type(z)

# Operações matemáticas
x + int(y)

x + y # retorna número do tipo float, caso precise ser inteiro, é necessário converter a variável de float para int

str(x) + z

str(y) + w

x + z  # Não podemos fazer operações entre números e string

# Estruturas de dados
d = {'nome': 'Jeanne', 'idade': 36, 'estado': 'RN'}

type(d)

d.keys()

d['nome']

d['estado']

L = [1,2,3,4,5]
type(L)

L[2] # retorna o valor localizado na terceira posição, pois no python inicia-se em 0

L[-1] # retorna o último elemento

L[-2] # retorna o penúltimo elemento

T = (520, 'coordenadas geográficas', 20, 84999781275) # a tuppla se diferencia da lista por não ser dinâmico, ou seja, os dados não são alterados, na lista pode ser modificado, por exemplo, lista de compras, lista de tarefas, etc
T

type(T)

T[2]